### ISSUE TITLE
Consider XML patch format for repository diff/merge utility

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#10]
The current implementation creates its own simple format for an XML diff file. In the interest of standardization, consider changing it to this proposed standard:  [An Extensible Markup Language (XML) Patch Operations Framework Utilizing XML Path Language (XPath) Selectors](https://tools.ietf.org/html/rfc5261). One benefit of the standard is that it is suitable for use with HTTP PATCH operation.

**Comment by jimnup** [comment]
If we can use an emerging standard instead of our own bespoke implementation we should do so. It would be good to get some opinions on the viability and usability of the Xml patching standard.

**Comment by jimnup** [comment]
Still we can share what appears to be a reasonable syntax for updates with the RFC, even if it is not widely adopted.

**Comment by jimnup** [comment]
Don - you may also want to look at the XQuery update syntax extensions. I have used them successfully and XQuery is widely supported.

**Comment by donmendelson** [comment]
XML patch operations conforming to RFC 5261 was implemented.
