### ISSUE TITLE
repository-quickfix : the attribute "required" is absent in the generated QuickFIX dictionary for "Group" elements

### ISSUE THREAD

**Issue by david-gibbs-ig** [FIXTradingCommunity/fix-orchestra#104]
QuickFIXJ expects that the "required" attribute is present for "Groups".  
FIX Orchestra supports the required attribute for group references
example
```
<fixr:groupRef id="2032" presence="required" added="FIX.4.4">  
 ref  <fixr:group id="2032" added="FIX.4.4" name="MDIncGrp" category="MarketData" abbrName="Inc">
```

repository-quickfix does not generate this attribute where the group is used

example
```
<component name="MDIncGrp"><group name="NoMDEntries">
```

Compare this to the QFJ dictionary for 50sp2
example
```
<component name="MDIncGrp">
      <group name="NoMDEntries" required="Y">
```

This causes a runtime exception in QuickFIX/J when processing the dictionary 

See also the branch https://github.com/david-gibbs-ig/quickfixj/tree/fix-orchestra
Please note this takes up to 9GB of memory and 1.5 hours to build but you can see the output of repository-quickfix in the target directory of the quickfixj-orchestra module.

**Comment by donmendelson** [comment]
The data dictionary generator *does* generate "required" attribute for group references within a message or as a nested group. However, what's at issue here, in Orchestra terms, is the NumInGroup field within a group definition. In a few cases in Repository 2010 Edition, it *is* marked as required. More commonly, there is a comment like `Required if NoMDEntries(268) > 0.` Currently, unified2orchestra does not carry forward the "required" attribute of a NumInGroup.

Under what circumstances should NumInGroup be considered required versus conditionally required? @kleihan your thoughts?

It would be easy to generate `required="N"` to satisfy QuickFIX.

**Comment by david-gibbs-ig** [comment]
Thank you for looking into this so promptly Don, 
it is messy to talk about since QuickFIX, QFJ have the element "group" with the name of the NumInGroup field. This is like what is seen in Fiximate. For legacy compatibility Is it the case that that where the GroupRef is required then the NumInGroup is there-by required and the QFJ dictionary "group" should be required. I think there is an implementation compatibility question here in how users of QuickFIx/QFJ may just request a "required" group rather than testing for the presence of the group.
thanks again

<component name="MDFullGrp">
      <group name="NoMDEntries" required="Y">

![image](https://user-images.githubusercontent.com/29655222/97883163-6a9e9680-1d1c-11eb-88b7-36f0c763e5e5.png)

**Comment by donmendelson** [comment]
This issue was raised in the GTC weekly tech meeting.

- It is true that in Repository 2010 Edition, a few `<repeatingGroup>` elements have "required" attribute set true, and that is shown in FIXimate, while the majority do not. Note that the Repository element is identified by NumInGroup tag.
- The `<groupRef>` elements in Orchestra have "presence" attribute set to required as in Repository. This tells whether the group is required by its containing message or parent group. No controversy here.
- This issue was discussed before, and it was decided *not* carry forward `<repeatingGroup>` "required" attribute to Orchestra `<numInGroup>` "presence" attribute in a group definition (although the property is allowed by the schema). Reasons:
    * NumInGroup is only used in tag-value encoding, not in SBE, FIXML, etc. Presence in tag-value messages is controlled by the encoding standard.
    * I contend that whether a repeating group is required is determined by the presence of a `<groupRef>`, where it is used and is not a property of the group itself. 

The tag-value encoding specification states:

```
The NumInGroup field is required and must be larger than zero if the repeating group is required, or if the repeating group is optional and the message contains one or more instances for that repeating group.
```

My opinion is not definitive. This issue is open for discussion.

**Comment by david-gibbs-ig** [comment]
Hi Don, that makes sense to me, my comment was not very clear. I wouldn't propose to change the Orchestra repository usage.  I think the anomaly is that QFJ refers to the ```<group>``` with the name of the ```<NumInGroup>``` field and does not have a field entry for the ```<NumInGroup>```, the two are conflated. I think this issue could be resolved if the required attribute for the ```<groupRef>``` can be bridged to the ```<group>``` definition (within the message so equivalent to groupRef) in the QFJ dictionary. I don't know if this is practical but it would be be consistent with QFJ usage.

```
<group name="NoMDEntries" required="Y">
```

**Comment by donmendelson** [comment]
@david-gibbs-ig I think that was the thinking in Repository. A problem is that a group may be used by multiple messages. What should happen if the group is required in one message but not in another? A quick skim of Repository revealed that it is internally inconsistent.

I agree that we need to populate the attribute to satisfy QFJ. What would be the impact if we always set it to required="N"?

**Comment by david-gibbs-ig** [comment]
@donmendelson  thanks, I think that if it is always set to 'N' then users of QuickFIX family dictionaries we will lose a little bit of compatibility with the standard expressed in FIX Latest. 

I might be making too much of it but in the example above, the repository tells us that we can rely on the MDIncrGrp being present and that if it is absent the message is malformed. Developers may have relied on this and not check for the presence of the ```<NumInGroup>``` (  i.e. ```NoMDEntries```  ), in other words leaving it to the FIX engine to validate the message. The handling of a malformed message can conceivably be different depending on the exception handling. Specifically in QFJ a malformed message may result in a null pointer exception in application code rather than the session level Reject message that would be thrown by QFJ message validation. This may or may not have the same end result, it depends on the application exception handling. 

If we generate a Rules of Engagement and other documents from FIX Orchestra they may say the Group is mandatory in a message, but the generated dictionary would contradict this.  I think it would be _ideal_ if a way can be found to carry the required attribute for the ```<groupRef>``` nested in the message in the orchestra repo to the ```<group ...>```  element nested in the ```<message>``` in the  QuickFIx dictionary.  If I understand, it's the ```<groupRef>``` required attribute that matters in this case .

**Comment by donmendelson** [comment]
Code added to set `<group>` required if there is *any* matching `<groupRef>` that is required.

**Comment by david-gibbs-ig** [comment]
Thanks Don,

I think that would make the Parties group ```fixr:group id="1012"``` required everywhere though.

I haven't managed to DataDictionaryGenerator yet, I've been reading it....

**Comment by david-gibbs-ig** [comment]
I've built this version so will try to  test it soon.

**Comment by david-gibbs-ig** [comment]
Hi Don, I tested the effect of the proposed change using QFj by changing around quickFIXJ.DataDictionaryTest. Where the component is not required, the presence of ```<group name="NoPartyIDs" required="Y">``` does not seem to have side effects.
When the component is required, the presence of ```<group name="NoPartyIDs" required="Y">``` is enforced in message validation. So I think that this is the behavior that we want.

**Comment by david-gibbs-ig** [comment]
Hi we've done the testing that we can and it has been successful. Could you please make a release of this fix-orchestra version ? Thank you
