### ISSUE TITLE
Add `servicepack` and `extensionpack` to `fix` element of generated data dictionary

### ISSUE THREAD

**Issue by chrjohn** [FIXTradingCommunity/fix-orchestra#106]
Currently the `DataDictionaryGenerator` generates only the `major` and `minor` version in the `fix` element.

https://github.com/FIXTradingCommunity/fix-orchestra/blob/3569faa06840472b649c447007f23d9ad36651d5/repository-quickfix/src/main/java/io/fixprotocol/orchestra/quickfix/DataDictionaryGenerator.java#L167-L168

This should be extended by at least `servicepack` and even better also `extensionpack`.
As far as I can see this information is available in the repository:
https://github.com/FIXTradingCommunity/fix-orchestra/blob/3569faa06840472b649c447007f23d9ad36651d5/repository-quickfix/src/main/java/io/fixprotocol/orchestra/quickfix/DataDictionaryGenerator.java#L149

The data dictionaries of QuickFIX (C++) already contain the `servicepack` attribute (it is `0` for non-SP versions):
http://www.quickfixengine.org/FIX50SP1.xml
http://www.quickfixengine.org/FIX50.xml

If it is OK with you I could provide a pull request.

**Comment by donmendelson** [comment]
Module moved to project FIXTradingCommunity/fix-orchestra-quickfix
