### ISSUE TITLE
[repository schema] sort attribute of codeType should be numeric

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#113]
The sort attribute is used enforce order on codes within a codeSet for documentation purposes only. (A set is by definition unordered.) It is currently of type string in the XML schema but should be nonNegativeInteger as it was in Unified Repository.

**Comment by kleihan** [comment]
The sort attribute is currently not described in the Technical Specification of Orchestra V1.0. Hence no need to make any changes for the imminent promotion of V1.0 to Technical Standard (from Draft Standard). Going forward, the question is whether we need to support such an attribute at all or if we can deprecate it. The alternative is to follow the concept for messages, components, and groups where the ordering is implicit by position in the Orchestra XML file.

**Comment by donmendelson** [comment]
There is also a group attribute for codes that presumably interacts with sort.

**Comment by jimnup** [comment]
We have found this useful for code sets. Worth further discussing. I found
it valuable.. We use it for rendering into FIXimate.

Perhaps there is an alternative representation.

I do like flexible structures, such as group.

"Sort" as a concept or attribute - one could likely argue equally for it or
against it.

**Comment by donmendelson** [comment]
There apparently was an error in creating the Orchestra 1.0 schema. There is an XML type for it, but it was not used:

```xml
<xs:simpleType name="Sort_t">
	<xs:restriction base="xs:nonNegativeInteger"/>
</xs:simpleType>
```
Since "sort" only appears once in the schema, I propose to eliminate the simple type and just set the attribute to nonNegativeInteger.

The broader question is whether sort should be eliminated entirely. I know that it is used to visualize code sets in FIXimate. If someone would like to propose elimination, or an alternative, please do so. For now, I will just fix the immediate error.

**Comment by kleihan** [comment]
I support the change to nonNegativeInteger v1.1. The error does go back to unified repository that also did not use Sort_t even though it was available:

`<xs:attribute name="sort" type="xs:string" use="optional"/>`

I suggest to defer the question of elimination to Orchestra v2.0. That gives us time to evaluate the impact of moving from Basic to Orchestra as master repository. For example, inserting a new code in between existing values (rare case) is somewhat of pain as multiple sort attribute values have to be changed for that.

**Comment by kleihan** [comment]
Implemented in RC1
