### ISSUE TITLE
Minimum Java version?

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#115]
This package has been recently built to produce a multi-release jar that links with either Java 8 or Java 11+ applications. The key difference is Java 9+ has the module system that Java 8 does not recognize. The MRJAR build works with toolchain configuration, but that procedure is not generally supported by IDEs. Moreover, there are incompatibilities between Java 8 and 11 libraries, notably with regard to XML binding (JAXB).  It would easier to support one consistent Java version, so long as it is Java 11 or later, rather than continuing MRJAR.

I would like feedback from users of this project. Would Java 11 minimum be acceptable, or are you prevented from moving off Java 8?

_Notes_
* Oracle no longer makes public updates for Java 8 although it remains in popular use.
* Every third Java version, starting with Java 11, is designated for long-term support (LTS).
* Java 15 is current, with 16 to be released in March.

**Comment by chrjohn** [comment]
> Oracle no longer makes public updates for Java 8 although it remains in popular use.

People can still get up-to-date OpenJDK8 builds at AdoptOpenJDK.
https://adoptopenjdk.net/support.html?variant=openjdk8&jvmVariant=hotspot#roadmap

That being said, we also still rely on Java 8 for some of our products but largely switched to Java 11+ for backend stuff.

QuickFIX/J is still being developed on Java 8. There have been one or two requests some time ago to support the module system but it never was implemented and actually it does not seem to be a big issue at the moment (although there are plans to support it at some time in the future).

But to answer your actual question: for me personally Java 11 would be acceptable.
