### ISSUE TITLE
Restricted characters in message and components Name_t

### ISSUE THREAD

**Issue by YuvalCohen** [FIXTradingCommunity/fix-orchestra#118]
The names of message and components in the repository is currently defined in the format of Name_t
Which is: ([A-Z]|[a-z])([0-9]|[A-Z]|[a-z]|_)* 

Our naming convention for messages and components is slightly different then FIX and require dot ('.') in the names of messages and components

Adding '.' to the Name_t near the underscore may be very useful.

**Comment by donmendelson** [comment]
Proposal:

```xml
<xs:simpleType name="Name_t">
  <xs:annotation>
	<xs:documentation>Names are from 1-64 characters. The XML processor will remove line feeds, carriage returns, tabs, leading and trailing spaces, and multiple spaces. Internal spaces are allowed by the schema but may be restricted by an external style.</xs:documentation>
  </xs:annotation>
  <xs:restriction base="xs:token">
	<xs:minLength value="1"/>
	<xs:maxLength value="64"/>
  </xs:restriction>
</xs:simpleType>
```

**Comment by kleihan** [comment]
Added text for naming rules

**Comment by kleihan** [comment]
Implemented for RC1
