### ISSUE TITLE
[repository schema] Support annotations as introductions to sections

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#121]
It is currently not possible to have introductory text for the complete section of messages, components, fields, code sets. Annotations are only supported for a specific message, component, field, code set. This capability would make it easier to have the RoE in markdown as master where complete sections can be populated with orchestra2md.

**Comment by kleihan** [comment]
Just to confirm, does the category element already have this capability? The newer categories like PartiesAction have some text:

```
       <fixr:category added="FIX.5.0SP2"
                     addedEP="171"
                     FIXMLFileName="partiesaction"
                     componentType="Message"
                     section="PreTrade"
                     includeFile="components"
                     name="PartiesAction">
         <fixr:annotation>
            <fixr:documentation purpose="SYNOPSIS">
         The PartiesAction category of messages is a set of messages that are used to take an action on party information as a result of risk management decisions made during the trading day.
      </fixr:documentation>
         </fixr:annotation>
      </fixr:category>

```

**Comment by jimnup** [comment]
The original vision was to be able to store text at the category level via
the annotation element.

**Comment by kleihan** [comment]
The online normative spec has text for categories that is not in Orchestra yet and vice versa (the above for PartiesAction is not available online). We can use the Orchestra tool to sync up the two sources (and do the same for sections).

**Comment by donmendelson** [comment]
To be clear,`<category>` element can have annotations, but not its parent `<categories>`. Same for other top-level elements such as `<fields>`.

**Comment by donmendelson** [comment]
See broader issue #127

**Comment by kleihan** [comment]
Implemented in RC1
