### ISSUE TITLE
[repository schema] latestEP attribute is redundant

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#122]
This attribute of `<fields>` is redundant to metadata for the repository

**Comment by kleihan** [comment]
I believe this is a legacy feature from the Basic repository that had separate files for abbreviations, datatypes, enums, fields, components, messages, message contents, categories, sections. All of these files hat latestEP as an attribute of their root element. It indicates the last time an element *within this group* was added or updated. It is redundant as the highest EP number can easily be determined by a script checking the pedigree attributes (e.g. addedEP, updatedEP) of its sub-elements.

If we remove it for fields then it should also be removed for all other elements in the list above. The root element of the files in the Basic repository also had an attribute "version" that was redundant and only exists once in the Unified repository.

**Comment by kleihan** [comment]
The attribute still needs to be removed from the fields element, correct?
```xml
	<xs:element name="fields">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="field" type="fixr:fieldType" minOccurs="0" maxOccurs="unbounded">
					<xs:key name="typeKey">
						<xs:selector xpath="."/>
						<xs:field xpath="@type|@codeSet"/>
					</xs:key>
				</xs:element>
				<xs:element name="annotation" type="fixr:annotation" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="latestEP" type="fixr:EP_t"/>
			<xs:attribute ref="xml:base"/>
		</xs:complexType>
                ...
```

**Comment by kleihan** [comment]
Implemented in RC1
