### ISSUE TITLE
Validator to inform about usage of deprecated fields

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra#126]
Enhance output of validator to list the deprecated fields found in the Orchestra XML file as a warning. This is useful when creating an Orchestra subset fro FIX Latest with PlayList as it will contain the deprecated fields that may have been picked in the PlayList GUI.

**Comment by donmendelson** [comment]
It would be useful to know if a fieldRef is *not* marked deprecated but its referenced field is. (I didn't find any in FIX Latest.)
