### ISSUE TITLE
[epository schema] Annotations for top-level elements

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#127]
Each actor and flow can have an annotation element, but the <actors> parent element does not have annotation in the Orchestra repository schema to hold documentation for all actors and flows. The same is true for other top level elements, including messages, fields, components, etc. We did not see the need for when creating the schema, but it would be useful to keep common documentation in Tablature round trips.

**Comment by kleihan** [comment]
Implemented in RC1
