### ISSUE TITLE
[repository schema] Propose to define identifier attributes as token

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#129]
Most identifier attributes in the repository schema are of XML Schema datatype "string". I propose that they should instead be of type "token" which suppresses leading and trailing whitespace and line breaks. It allows internal spaces, but replaces multiple spaces with a single space.

See https://www.w3.org/TR/xmlschema11-2/#token

**Comment by kleihan** [comment]
Would that only apply to the mapped datatype, i.e. not to the "normal" datatype used by tagvalue syntax?

**Comment by donmendelson** [comment]
@kleihan, this proposal is not specific to FIX datatypes, but rather to any string-like attribute in the XML schema, e.g. name, abbrName, scenario, etc. Token is a subclass of string XML schema datatype that restricts it for naming purposes.

**Comment by donmendelson** [comment]
Many identifiers are already covered by proposal for changing Name_t issue #118. However, there are also XML types for abbreviated names and scenario names. I propose that they also use the modified Name_t as there type.

**Comment by donmendelson** [comment]
Apply to interfaces schema as well.

**Comment by kleihan** [comment]
Implemented in RC1
