### ISSUE TITLE
[repository schema] Allow name in fieldRef, groupRef, componentRef

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#136]
This has been entered as an issue in fix-orchestra-spec https://github.com/FIXTradingCommunity/fix-orchestra-spec/issues/27.

Propose to add name as optional attribute in attribute group `refidGrp`. It is include in fieldRef, groupRef, componentRef, and messageRef (used in responses).

**Comment by donmendelson** [comment]
The optional name is for convenience but will not be enforced by referential integrity. Only the name in a referred object (field, component, group, message) is authoritative.

**Comment by kleihan** [comment]
Implemented in RC1
