### ISSUE TITLE
[interfaces schema] document effective date of an interface

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#149]
For auditing, analysis, and other purposes, messages need to be stored for a long time, perhaps years. How can they be brought out of archive and correlated to scenarios in a ROE that was perhaps published years ago but changed many times since?

I propose to add an effective date-time to a defined interface that could be used to correlate an interface version to a message that was captured on a certain date. Since session configurations already have a concept of "activationTime" and "deactivationTime", we can reuse those concepts for service offerings and orchestration versioning.

Also, the working group proposed adding a "deprecated" attribute to an interface to inform users that a service offering may be removed or replaced in the future.

**Comment by kleihan** [comment]
Implemented in RC1
