### ISSUE TITLE
[repositorySchema] mappedDatatype lacks size attribute

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#152]
The mappedDatatype element specifies how a FIX datatype maps to a message encoding. Most of the elements originated in the Unified Repository schema that were originally used to map FIX to XML Schema. Orchestra was enhanced to map to any FIX or other encoding, such as SBE or Google Protocol Buffers. There is at least one gap, however, the lack of a size or length attribute. SBE and other encodings support fixed-length fields. For example, Symbol field could be fixed to 6 characters for equities. Proposal is to add a size attribute.

More comprehensively, a review of all attributes of mappedDatatype should be made in view of [ISO 11404 General Purpose Datatypes](https://www.iso.org/standard/39479.html), a taxonomy of datatypes, to make sure all needs are met.

**Comment by donmendelson** [comment]
ISO 11404 refers to the *size* of a sequence and other aggregate types, so it seems that term is more generic than *length*.

**Comment by donmendelson** [comment]
Adding some comments to the XML schema for attributes of mappedDatatype:

**base** - A datatype from which a subtype may be created by restriction or a derived type is created by a generator
**pattern** - A lexical restriction from a base type
**element** - Element type of an aggregate type such as an array or sequence

**Comment by donmendelson** [comment]
I question the utility of Boolean **builtin** attribute. It seems to imply that it need not be explicitly defined in the target encoding. Even if that is the case, we still need to map to something in the encoding, which would be defined as a **base** type.

**Comment by donmendelson** [comment]
Example using proposed size attribute:
```xml
<fixr:datatype name="String" scenario="equities" scenarioId="5">
	<fixr:mappedDatatype standard="SBE" base="char" size="6">
		<fixr:annotation>
			<fixr:documentation purpose="SYNOPSIS">
         A character array of size 6 for an equity symbol
			</fixr:documentation>
		</fixr:annotation>
	</fixr:mappedDatatype>
</fixr:datatype>
```

**Comment by donmendelson** [comment]
The mappedDatatype element also lacks an attribute for void representation in data structures where presence is optional. This case was encountered in mapping of SBE datatypes that have a configurable `nullValue` attribute.

In the ISO 11404, an Optional datatype is described as "all values v of the base datatype plus the “nil value” of void."

**Comment by kleihan** [comment]
Implemented in RC1
