### ISSUE TITLE
[repository schema] Field type attribute does not distinguish between datatype and code set reference

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#170]
Comment by Emil Rakadjiev in Orchestra working group collaboration:

...based on our experience with developing tooling around Orchestra, it's awkward to handle in the code. It has also been a source of confusion within our development team several times. Which I think is a sign for a "code smell".
Using a more explicit reference - mostly for the code set's scenario, but ideally also for whether it's a datatype or a code set - would be helpful in my opinion.

**Comment by kleihan** [comment]
Cleaner modelling to distinguish types from code sets explicitly. Conversion from v1.0 should be straightforward, changing `type="xxxCodeSet"` to `codeSet="xxxCodeSet"`. Find instances with regular expression `type=".*CodeSet"`

**Comment by kleihan** [comment]
Implemented in RC1
