### ISSUE TITLE
[repository schema] Names of codesetRefKey and codesetKeyref

### ISSUE THREAD

**Issue by kleihan** [FIXTradingCommunity/fix-orchestra#174]
All names except these two use camel case for code sets, i.e. `codeSetxxx`. Is this intentional?

**Comment by donmendelson** [comment]
I have no objection to normalizing capitalization.

**Comment by kleihan** [comment]
Proposal to change the spelling of `codesetRefKey` and `codesetKeyref` to `codeSetRefKey` and `codeSetKeyref`.
