### ISSUE TITLE
[repository schema] Missing AppInfo FIXML schema (for EP272 and higher Orchestra XMLs)

### ISSUE THREAD

**Issue by erakadjiev** [FIXTradingCommunity/fix-orchestra#179]
Starting from the FIX Latest EP272 Orchestra XML, AppInfo elements with FIXML information are included. For example, this `FIXMLencodingType` tag:

![image](https://user-images.githubusercontent.com/8909422/222094279-5a4fdbcc-6340-497d-804c-65cf5959ad6d.png)

The XSD corresponding to the `http://fixprotocol.io/2022/orchestra/appinfo/fixml` namespace is not included in `repository/src/main/resources/xsd/`, thus generated Java bindings are not available for those elements. When the XML is unmarshalled, those FIXML tags are represented by generic `com.sun.org.apache.xerces.internal.dom.ElementNSImpl` objects. Those objects lead to various issues during later processing of the document.

It would be good to include the FIXML-related XSD as well, so that Java bindings are generated for it. This would also require publishing a new Maven module (version 1.7.4).

**Comment by erakadjiev** [comment]
I think we should reject this issue, because the FIXML AppInfo elements shouldn't be considered a part of the Orchestra Repository and thus we shouldn't include the FIXML AppInfo XSD with the other Orchestra Repository XSDs.

By the way, is the XSD for the FIXML AppInfo elements (`http://fixprotocol.io/2022/orchestra/appinfo/fixml`) available somewhere? I think having it would be sufficient to make working with those elements a bit more convenient.

**Comment by patricklucas** [comment]
I concur that this issue can be closed per @erakadjiev's last comment.

@erakadjiev I found these comments from 2022: https://github.com/FIXTradingCommunity/orchestrations/issues/30#issuecomment-1271734274

So it seems there is not a public XSD for that, but as @kleihan notes there, the namespace is chiefly an identifier, and @donmendelson notes that it is used in a place in the Orchestra XSD that should allow any element. So IMO everything here is "above board", and the `appinfo` parts of the published Orchestra spec for FIX should be considered implementation details specific to FIX.

**Comment by erakadjiev** [comment]
Thank you @patricklucas !

I still think that publishing the schema for the official FIXML extensions can be useful to some users.
However, that's unrelated to the Orchestra schema, so I'll close this ticket.
