### ISSUE TITLE
Scenarios for components

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#18]
In the Orchestra model, messages currently may have multiple scenarios (use cases) with different layouts, but components do not. But it would be a useful feature to allow multiple flavors of a component. For example, an Instrument block would have a different set of fields depending on asset class. Like messages, the different scenarios of a component would share the same name, supplemented by scenario name, but would be uniquely identified by a different numeric ID.

**Comment by kleihan** [comment]
Sounds reasonable but increases complexity, multiple scenarios need to be combined to make up a single message. The message defines the main scenario whereas the component scenarios need to be sub-scenarios for the scenarios of the message they are in. In terms of modeling I see a gap in between message and component scenarios, i.e. repeating groups being used as a simple component with a single instance (regardless of the details of which fields are used from inside the component). Orchestra should allow to explicitly model that, not just implicitly by means of cardinality=1.

Background is the dilemma we face with every extension where the submitter only needs a single instance and we (FIX) decide to rather create a repeating group as we cannot change it later. This is driven by the legacy tag=value and FIXML encodings where a change to a repeating group causes breakage. It would be great if we could offer some flexibility here to model a component as repeatable or not for a given encoding (or all encodings). For example, the Instrument component is non-repeatable for all encodings except when it is part of an outer repeating group. On the other hand, the CommissionData component could not be made repeatable and we had to introduce CommissionDataGrp as an additional component and define rules as to when to use which component.

**Comment by donmendelson** [comment]
The consensus of the Asia/Pac meeting was to go forward scenarios for components. For some asset classes, the instrument definition requires currency and exchange, for example.
