### ISSUE TITLE
[interfaces schema] Typo in field type "userIntefaceType" should be "userInterfaceType"

### ISSUE THREAD

**Issue by philipwhiuk** [FIXTradingCommunity/fix-orchestra#181]
See 
https://github.com/FIXTradingCommunity/fix-orchestra/blob/76f5dc758c1f5f990d4d0c2444f61371a232dae0/interfaces/src/main/resources/xsd/interfaces.xsd#L302

**Comment by kleihan** [comment]
We normally keep all issues open until the related document (v1.1 RC1 in this case) has been approved by the GTC for public comment. We then close all of them at once and work continues on the next RC.

**Comment by kleihan** [comment]
Implemented in RC1
