### ISSUE TITLE
[repository schema] Consider moving "Datatype" from repository.xsd's root level to repositoryType.xsd

### ISSUE THREAD

**Issue by francescoloconte** [FIXTradingCommunity/fix-orchestra#190]
The _repository.xsd_ file, allows containers for various elements at the root level, like _Messages_, _Elements_, _Datatypes_, etc. However, it also allows the Datatype element at the root level. Does this have a use case? Or should the Datatype be moved to the _repositoryTypes.xsd_ file instead, where all other types reside?

![image](https://github.com/FIXTradingCommunity/fix-orchestra/assets/41475981/6466ffc0-5ba3-4c23-9267-ec3c554af188)

**Comment by francescoloconte** [comment]
Hello everyone. It would be useful if anyone could identify a use case for keeping _datatype_ in _repository.xsd_. I could not find one and I am suggesting that we move it to _repositoryType.xsd_, where all other types are described.

**Comment by patricklucas** [comment]
I don't think `datatype` being defined in `repository.xsd` allows a `<fixr:datatype />` element at the root of a _repository_, as the definition for `repository` still only includes `datatypes`, not `datatype`.

But I do agree that, for consistency with all the other second-level repository elements, we should move `datatype` into `repositorytypes.xsd`. As far as I understand, this should have no effect on users of these XSDs, as they are both defined in the same namespace, so even generated code would be in the same Java package, for instance—I believe the separation of the two XSD files is purely organizational.
