### ISSUE TITLE
messageAttribGrp is not used.

### ISSUE THREAD

**Issue by francescoloconte** [FIXTradingCommunity/fix-orchestra#192]
The _messageAttribGrp_ is not used anywhere. However, _rendering_, _category_, and _abbrName_ attributes are present separately in _componentType_ and _groupType_, but not in _messageType_. It would be useful to have them.

![image](https://github.com/FIXTradingCommunity/fix-orchestra/assets/41475981/60837fd1-e88a-4f8e-8bfd-3bcbfafe7458)

**Comment by kleihan** [comment]
Duplicate to #189
