### ISSUE TITLE
[repository schema] Some simple types are not used.

### ISSUE THREAD

**Issue by francescoloconte** [FIXTradingCommunity/fix-orchestra#195]
The following types are defined in the schema but they do not seem to be used anywhere:

<xs:simpleType name="CategoryComponentType_t"> 
      <xs:restriction base="xs:string">
            <xs:enumeration value="Field"/>
            <xs:enumeration value="Message"/>
      </xs:restriction>
</xs:simpleType>

<xs:simpleType name="CompID_t">
      <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1000"/>
      </xs:restriction>
</xs:simpleType>

<xs:simpleType name="GroupName_t">
      <xs:restriction base="xs:string"/>
</xs:simpleType>

<xs:simpleType name="IncludeFile_t"> 
      <xs:restriction base="xs:string">
            <xs:enumeration value="components"/>
            <xs:enumeration value="fields"/>
      </xs:restriction>
</xs:simpleType>

**Comment by francescoloconte** [comment]
@kleihan , if these simple types are not used in the schema, is this a sufficient reason to remove them? Or can there be other reasons for which they should remain even if not used? There may be aspects of the standard am I not familiar with, that justify these staying in the schema. If you confirm they can be removed, I would submit a PR to remove them, and close this ticket.

**Comment by patricklucas** [comment]
I can confirm that these are all unused, likely vestigial from Unified, and concur they can be removed.
