### ISSUE TITLE
Java compiler to use for FIX Orchestras code

### ISSUE THREAD

**Issue by nriyait** [FIXTradingCommunity/fix-orchestra#21]
Which Java compiler is required to compile the .java code files for FXI Orchestra test code ?

**Comment by philipwhiuk** [comment]
I'm not sure whether it's worth targeting Java 9 or 10 given they are only supported until the following release. Sticking to Java 8 until Java 11 (which is an LTS release like Java 8) seems more sensible.

**Comment by donmendelson** [comment]
Apparently the plan is to remove XML from the run-time entirely in Java 11. Then it will be linked into a project like any other library. The only impact is that it will versioned independently of the JRE.
