### ISSUE TITLE
How to define rules

### ISSUE THREAD

**Issue by onurkaraduman** [FIXTradingCommunity/fix-orchestra#24]
I checked everywhere but I couldn't find any example about the following. 
For example I have  tag ExpireTime(126) and TimeInForce(59). The tag ExpireTime(126) should be required if TimeInForce(59) is defined. How can I define this kind of rules in orchestra file?

**Comment by donmendelson** [comment]
Do you mean ExpireTime is required if TimeInForce = GTD?

**Comment by onurkaraduman** [comment]
Yes, in that kind of cases.

**Comment by kleihan** [comment]
In this case it would be a little more complex as there is more than one option when using TimeInForce(59) = 6 (GTD). It requires either ExpireDate(432) if only a date is relevant or ExpireTime(126) if only a time or both date and time are relevant. However, a given implementation may define a rule that only ExpireTime is supported and midnight (00:00:00.000...) is to be used if it is only about the date.

**Comment by onurkaraduman** [comment]
@kleihan  thanks for reply. 
So you mean there is no kind of rule or validation module in current implementation. 

@donmendelson Is there any plan to get this feature live?

**Comment by kleihan** [comment]
@onurkaraduman no, I explained what the rule should be from the perspective of FIX semantics. Not sure if it makes sense to design a rule that defined a range of valid values for the time portion of the data type UTCTimestamp. It is easier to define the special handling of midnight in the written Rules of Engagement.

**Comment by donmendelson** [comment]
The feature for conditionally required fields is already available in Orchestra. It is specified by adding a child `<rule>` element with `presence="required"` attribute to a `<field>` or `<fieldRef>` element. The rule then contains a `<when>` element with a predicate expressed in the Score DSL. When the expression evaluates to true, then the field is required.

Example:
```xml
<fixr:fieldRef id="126" name="ExpireTime">
	<fixr:rule name="ExpireTimeRequired" presence="required">
		<fixr:when>TimeInForce== ^GoodTillDate</fixr:when>
	</fixr:rule>
</fixr:fieldRef>
```
Notes:
* In this example, the rule is on a fieldRef for an instance of ExpireTime in a message. If the rule is global to every instance of ExpireTime, then the rule could be defined in the field definition.
* In the DSL expression, "TimeInForce" refers to that field in "this" message by default. It is also possible to qualify the field name with "in" or "out". A rule or assignment of a field in an outgoing message can refer to a field value in an incoming message, for example.
* The ^ symbol means that the following token is a symbolic name of a code (formerly enum in Repository 2010 Edition). Alternatively, the literal value of the code, in this case "6", can be used in the expression, but the symbolic name is more understandable.

**Comment by onurkaraduman** [comment]
@donmendelson 
small edit: We have to add  presence="conditional" to field ExpireTime as in the following, otherwise it doesn't work for docGen.
```
<fixr:fieldRef id="126" name="ExpireTime"  presence="conditional">
	<fixr:rule name="ExpireTimeRequired" presence="required">
		<fixr:when>TimeInForce== ^GoodTillDate</fixr:when>
	</fixr:rule>
</fixr:fieldRef>
```

I tested this rule with docGen and it works. But I don't understand how to generate a java class with this rule. I mean how validation throws exception if the condition is not satisfied during the development.

**Comment by donmendelson** [comment]
Thanks for the correction.

How to generate classes from the declaration of rules is a decision for implementers and is not dictated by the Orchestra standard. However, look at the Validator class in module model-quickfix for a suggestion.

The action taken when a rule is violated, such as a type of rejection message to be sent, should be declared in Orchestra rules of engagement.
