### ISSUE TITLE
How to generate orchestra file from fix dictionary and fix session config file

### ISSUE THREAD

**Issue by onurkaraduman** [FIXTradingCommunity/fix-orchestra#26]
I am trying to create orchestra file for a project which has currently fix dictionary and fix session config file. Is there any way to generate automatically fix orchestra file from fix dictionary and fix session configuration file?

**Comment by onurkaraduman** [comment]
This is my fix session config file:
QuickFixConfiguration.ini
```
[DEFAULT]
[SESSION]
ConnectionType=initiator
TargetSubID=
BeginString=FIXT.1.1
TargetLocationID=
SenderSubID=
TargetCompID=ABC
SocketConnectHost=10.96.1.2
SenderCompID=XYZ
SenderLocationID=
SocketConnectPort=567

```

This is my dictionary:
FIX50SP2.xml
```
<fix major="5" minor="0">
  <header/>
  <trailer/>
  <messages>
    <message name="ExecutionReport" msgtype="8" msgcat="app">
      <component name="ApplicationSequenceControl" required="N"/>
      <field name="OrderID" required="Y"/>
      <field name="OrderRequestID" required="N"/>
      <field name="MassOrderRequestID" required="N"/>
      <field name="SecondaryOrderID" required="N"/>
      <field name="SecondaryClOrdID" required="N"/>
      <field name="SecondaryExecID" required="N"/>
      <field name="ClOrdID" required="N"/>
      <field name="QuoteMsgID" required="N"/>
      <field name="OrigClOrdID" required="N"/>
      <field name="ClOrdLinkID" required="N"/>
      <field name="MDEntryID" required="N"/>
      <field name="QuoteRespID" required="N"/>
      <field name="OrdStatusReqID" required="N"/>
      <field name="MassStatusReqID" required="N"/>
      <field name="HostCrossID" required="N"/>
      <field name="TotNumReports" required="N"/>
      <field name="LastRptRequested" required="N"/>
.
.
.
.
```

**Comment by donmendelson** [comment]
Data dictionary to Orchestra transform does not currently exist in this project, but Orchestra to QuickFIX data dictionary is demonstrated in module repository-quickfix. You should be able to derive the associations from that project and reverse the flow. A contribution would be welcome.

Be aware that Orchestra has a much richer schema than QuickFIX. For example, fields in QuickFIX are only described as required = Y/N while in Orchestra field presence is one of optional/required/conditional/forbidden/ignored/constant. Furthermore, Orchestra has an expression language to specify when a conditionally required field is in fact required.
