### ISSUE TITLE
Key fields for message correlation

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#28]
Orchestra could benefit from identification of key fields in a message to link an execution to an order, for example. (It already has syntax to define uniqueness of keys.) Sometimes there are alternative keys, such as ClOrdID and OrderID.

**Comment by kleihan** [comment]
An important distinction is the issuer of the identifier, i.e. it can be the sender or the receiver of a message. Better the initiator of and responder to a workflow. Changes often require the submitter of the change to use both identifiers (his own and the one issued by the counterparty for the same entity).

More generaly, the topic is about message versus entity identifiers and submitter- versus receiver-issued.

**Comment by donmendelson** [comment]
That are multiple use cases for keys to correlate messages:
- Correlate response to request, e.g. CrossRequestID field ties CrossRequestAck to a CrossRequest message.
- Correlate an update to a replaced version, e.g. IOIRefID ties to IOIID of an updated IOI.
- Correlate an aggregation to an element, e.g. AffectedOrderID ties to OrderID of order messages affected by a mass action.
- To Hanno's point, often there are multiple IDs assigned to the same transaction by multiple parties, e.g. ClOrdId and OrderID.

Now I'm thinking that keys are an aspect of workflow rather than a property of a message in isolation. The `<response>` element of workflow could convey which IDs are assigned on that response. For example, when an order is entered, an accepted response would assign OrderID while an immediate trade would also assign ExecID.
