### ISSUE TITLE
More efficient identifier structure

### ISSUE THREAD

**Issue by Olivercomputing** [FIXTradingCommunity/fix-orchestra#36]
Previously, a system using lengthy globally unique identifiers on many elements in an Orchestra file was considered. Discussion with Jim Northey and Don Mendelson led to the thought that this was excessive, in terms of required processing power and file size, and possibly other issues.

The conclusion drawn is that a globally unique identifier for each new Orchestra file, specified in a top level element, would suffice to differentiate each element, via appropriate concatenation of that id with elements in the file (such as GUID+Field+Field_id) 

The identifier might itself be comprised of an organizational unique identifier, potentially assigned by FPL organization, plus a further random, unique GUID to ensure uniqueness per file globally.

**Comment by donmendelson** [comment]
The unique file identifier can be provided in the metadata section. Dublin Core Term "identifier" is suitable for this purpose. It is defined as:

> An unambiguous reference to the resource within a given context.
