### ISSUE TITLE
Update build to current Java version

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#38]
The current Java version is 10, version 11 is planned for release in Sept. 2018, and subsequent releases are planned at 6 month intervals. The Orchestra project code was originally built with Java 8. Oracle is making no more updates for older versions, although commercial support continues for another year. The main difference going from version 8 to later versions is the introduction of the [module system](https://www.oracle.com/corporate/features/understanding-java-9-modules.html) in Java that requires some adjustments to the build procedure.

**Comment by donmendelson** [comment]
I have discovered in [Project Conga](https://github.com/FIXTradingCommunity/conga) that many tools such as Maven plug-ins still do not support Java modules that were introduced in Java 9. Since XML was moved out of the Java base library into a separate module, it is certain that we would need to *use* modules even if we do not create our own for Orchestra.

**Comment by donmendelson** [comment]
I propose to defer this until after the release of RC4.

**Comment by donmendelson** [comment]
Issue: JAXB utility xjc has been removed from the JDK 11 distribution. A newer or different Maven plugin is needed that references it as an external dependency.

**Comment by donmendelson** [comment]
Deferring until Maven plug-ins mature and libraries take account of module system.

**Comment by brainopener** [comment]
Master (dbb1a4d5c0817eab314f857dbdf57e71f7744934) builds and tests pass on OpenJDK 11.0.6 with these dependencies added to the root `pom.xml`:

``````````
        <dependency>
            <groupId>javax.xml.bind</groupId>
            <artifactId>jaxb-api</artifactId>
            <version>2.3.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-core</artifactId>
            <version>2.3.0.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-impl</artifactId>
            <version>2.3.2</version>
        </dependency>
        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
            <version>1.1.1</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
``````````

**Comment by donmendelson** [comment]
Thanks @brainopener. I'm thinking that I'll create the next release build keeping Java 8 minimum. Then update for the next build. (We expect to publish Orchestra version 1.0 Draft Standard very soon.)

**Comment by donmendelson** [comment]
@brainopener I expect the Sun code is frozen in amber. Considering switching to the org.glassfish implementation of JAXB going forward, which should be maintained. Do you have any experience with this?

**Comment by donmendelson** [comment]
Hmm. I'm running into the problem described here https://github.com/eclipse-ee4j/jaxb-api/issues/78.

**Comment by brainopener** [comment]
@donmendelson 

I tried this in a sandbox environment. Here's the setup:
- AWS spot instance in Oregon region
- Ubuntu 18.02 OS
- [Forked](https://github.com/brainopener/fix-orchestra) `fix-orchestra` and made changes to `pom.xml`.

Here are the commands that I ran on it:
`````
sudo apt update
sudo apt-get install graphviz git openjdk-11-jdk maven -y
git clone https://github.com/brainopener/fix-orchestra.git
cd fix-orchestra
mvn package 
`````

What I see is that Maven builds it and runs the tests successfully.

The shell log is [here](https://github.com/brainopener/fix-orchestra/blob/master/openjdk11-build.txt).
A video of the process is [here](https://github.com/brainopener/fix-orchestra/blob/master/openjdk11-build.mp4).

**Comment by donmendelson** [comment]
@brainopener thanks for your help. I'm making progress on building the Maven repository module as a Java module for Java 11+ and having an application use it. The goal is to build with just modules rather than classpath so we can use jlink and jpackager for images, installers, etc.

FYI I am splitting off the validator and compressor utilities into a separate module to reduce dependencies of just repository.

**Comment by donmendelson** [comment]
It's apparent that this code can be compiled in Java 11 and 14, but many libraries and tools are not ready for prime time. I was hoping to build an application with runtime image and installer using jpackager in Java 14. This requires Java modules but many libraries are not yet modular. Jakarta implementations of java.xml.bind and related dependencies are now being built with module declarations, but are in beta or milestone versions. I'll keep this work in a fork, but will wait for dependencies and tools to settle down.

**Comment by donmendelson** [comment]
Surveys show that the majority of firms are still using Java 8. We don't want to prevent them from using Orchestra code. Meanwhile, Java 9 and later moved XML out of the main Java library and added a module system. The ideal is to work for Java 8 *and* later versions that require module declarations. Investigating whether a multi-release jar might be a solution.
