### ISSUE TITLE
Separate components and groups

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#41]
As in the Unified Repository, the current Orchestra XML schema mixes component and repeating group definitions under one parent element, `<components>`. Phil Oliver proposed that we separate them into two paths: `<components>/<component>` and `<groups>/<group>`.

**Comment by kleihan** [comment]
I am in favor of the change but would like to know the impact on inline component references for FIXML (see EP105 Appendix D for details). For example, InstrumentLegGrp would become a group containing the component InstrumentLeg. The optimization changes

`<Leg>`
`<Leg Sym="AAPL"/>`
`</Leg>`

to

`<Leg Sym="AAPL"/>`

Could the optimization still apply or is this an issue as it now goes across two different element types?

**Comment by rshriver** [comment]
@donmendelson - Can you confirm our approach to generating FIXimate (and perhaps FIXML as well) at least for the interim, is to generate a Unified format export from Orchestra?  And then we would use the Unified export from Orchestra as the input into the FIXimate (FIXML) generation code.

**Comment by donmendelson** [comment]
Is the boolean attribute `hasComponents` necessary? You could simply test for the presence of `<components>` element?
