### ISSUE TITLE
Tooling for FIX members

### ISSUE THREAD

**Issue by domcc** [FIXTradingCommunity/fix-orchestra#52]
Could someone please advise how FIX members can get the FIX Orchestra tooling that allows you to generate Orchestra files from existing log files? I understand that some of the tooling like this is only available to FIX members.

Thanks,
Dominic

**Comment by donmendelson** [comment]
The log2Orchestra tool is undergoing internal testing. The Global Member Services Subcommittee is deciding on how to make this tool available to members.
