### ISSUE TITLE
Scenario names should not allow special characters

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#54]
Currently, scenario names are defined in the XML schema as datatype xs:string. However, web-base tools  for Orchestra, such as documentation generators, may turn element names and their scenarios into URL links. The string type allows almost any characters, including line feeds, carriage returns, and tab characters. However, URLs are more restrictive. RFC 3986 defines sets of reserved characters as follows.

> reserved    = gen-delims / sub-delims
> gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"
> sub-delims  = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

I propose that scenarios should be restricted to the same XML type as elements since it would restrict them to characters that are safe for URLs. That type is called Name_t and is defined as follows:

> <xs:simpleType name="Name_t">
> 	<xs:restriction base="xs:string">
> 		<xs:minLength value="1"/>
> 		<xs:maxLength value="255"/>
> 		<xs:pattern value="([A-Z]|[a-z]|_)([0-9]|[A-Z]|[a-z]|_)*"/>
> 	</xs:restriction>
> </xs:simpleType>

**Comment by donmendelson** [comment]
We might consider liberalizing Name_t to allow hyphens or underscores since they are legal characters in a URL. Then a scenario names could be formed like "SecurityType-Future" or "ExecType_Canceled".

**Comment by kleihan** [comment]
Agree with your assessment and suggestion to allow hyphens and underscores for more options to separate core name from names for scenarios.
