### ISSUE TITLE
Concept names may be non-unique

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#63]
Currently, concept elements are constrained in the XML schema to have unique name attributes. However, there may be more than one encoding that corresponds to the same concept. Therefore, the unique key constraint should be removed.

Example: In FIX 4.2 there were values of ExecType for PartialFill and Fill. These were replace in FIX 4.4 with one value Trade. Using the newer term, the concept is Trade. However, it would have two encodings in FIX 4.2, one with 150=1 and another with 150=2.

**Comment by philipwhiuk** [comment]
How would the tool then decide which value to use when sending to a FIX.4.2 session in this scenario? You'd adding the ambiguity back in.

**Comment by donmendelson** [comment]
An alternative would be to have two concepts in FIX 4.4 named PartialFill and Fill that happen to have the same encoding 150=F (Trade). The downside of this approach is that it requires planning across FIX versions to arrive at the concepts.

I am currently going through that exercise guided by FIX 4.4 Appendix 6-F "Replaced Features and Supported Approach". I will add the concepts to [fix-vocabulary](https://github.com/FIXTradingCommunity/fix-vocabulary).

**Comment by donmendelson** [comment]
It is inevitable that a concept name will have multiple meanings in different contexts. For example, in the current FIX vocabulary, "Investor ID" has two definitions, one for CIV and another for equities. @philipwhiuk, I agree that lookup should not be ambiguous, but either names have to altered to make them unique, or they need to be qualified by context. That would be analogous to using "scenario" as a qualifier for multiple definitions of the same MsgType.

**Comment by philipwhiuk** [comment]
It's worth trying to avoid non-unique concept names as much as possible - qualifying is probably better - but yeah if it's either unavoidable or trivially obvious which is right it's probably okay :)

**Comment by kleihan** [comment]
The concept(s) do(es) not need to change with the FIX version. They may be represented differently by legacy FIX version compared to FIX legacy. The top concept here is that of an execution or trade (FIX does not really make a clear distinction, i.e. it was called executions until FIX 4.3 came along with the TradeCaptureReport. Then it became blurry). There are two sub-concepts of an execution if you will, i.e. a partial fill and a fill. FIX 4.2 represented these sub-concepts in different ways, i.e. two values of ExecType whereas FIX 4.4 decided to use only only value of ExecType for both, requiring OrdStatus to be included to distinguish the two concepts.

**Comment by kleihan** [comment]
Sorry, "...by legacy FIX version compared to FIX Latest."

**Comment by kleihan** [comment]
What is the difference between a CIV investor and an equities investor from a conceptual point of view? I only see one entry for "Investor ID" in the vocabulary which is too limiting by the way (only allows numeric entries, i.e. clashes with data type of PartyID(448) and PartyRole(452)=5 (Investor ID)).

**Comment by donmendelson** [comment]
Let me illustrate with an example from another financial industry vocabulary: "Principal" can mean either a party role for proprietary trading, the amount of a loan, or the face value of a bond, depending on context. "Option" is another word that has multiple meanings.

FIBO vocabulary has more than one definition of some terms. They distinguish them by domain/subdomain and other properties.

**Comment by kleihan** [comment]
@donmendelson agree about different meaning of terms. I would prefer if "concept" is not identical to a "term", allowing us to say that names of terms may be non-unique but names of concepts are unique. A concept would then be larger than a term. But I am not familiar enough with vocabularies such as FIBO to know whether such a distinction is a good idea.

**Comment by donmendelson** [comment]
Withdrawing this request. I am now persuaded that we should keep the current unique key constraint. If necessary, we can append a suffix to a name for uniqueness if it applies within a certain context such as asset class.
