### ISSUE TITLE
Example file has fields after StandardTrailer

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fix-orchestra#69]
Example file mit_2016.xml has some message structures with some fields after StandardTrailer (componentRef id='1025').

**Comment by donmendelson** [comment]
There is no built-in check for this in the XML schema. The order of members of a message or component is the natural order in which they are listed in the XML file.

**Comment by donmendelson** [comment]
A larger issue is whether the header and trailer should be required in an Orchestra file at all since StandardHeader and StandardTrailer are specific to tag value encoding. Other encodings either have no header/trailer or a different one.

**Comment by kleihan** [comment]
The standard trailer should be tied to tagvalue encoding only, similar to the EncodedXXX fields. This is a Phase 2 spec feature, i.e. to produce versions that are specific to encodings (e.g. FIXML has no NoXXX fields). Do we still have the NoFIXML attribute in Orchestra?

The standard header is the most difficult one to get rid of as it is an integral part of FIX 4.x and many with FIX 5 do selectively use header fields to provide information to the application layer. They should not but we cannot ask them to simply get rid of them. Another option is to move the relevant ones into the body of a message. This has no impact on tagvalue but on most/all? of the other encodings.

**Comment by donmendelson** [comment]
See open issue Syntax for header and trailer inclusion #27

**Comment by francescoloconte** [comment]
Similarly to my comment to issue #27 , is this still an issue? Orchestra allows the inclusion of headers/trailer as normal components, since that is what they are. In the case of SWIFT mit_2016.xml, the author is free to add any element after the StandardTrailer. If my comment is correct, this issue can also be closed.
