### ISSUE TITLE
Can two fields have the same name? (General question: uniqueness in orchestra)

### ISSUE THREAD

**Issue by YuvalCohen** [FIXTradingCommunity/fix-orchestra#79]
Please provide the recommended practices for the following question:

1. Can two fields have the same name? 
Please indicate if the answer is different for message, component, codeset or group.

1. Can objects of different types (e.g. a message and a field) share the same ID ? or should ID be unique within an orchestra repository?

**Comment by donmendelson** [comment]
1. Uniqueness is enforced by the Orchestra XML schema using the **key** token. For message elements, these are uniqueness constraints:

- Code name within a code set.
- Code set name + scenario
- Code set id + scenario
- Component name + scenario
- Component  id + scenario
- Field name + scenario
- Field id (tag) + scenario
- Group name + scenario
- Group id + scenario
- Message name + scenario
- Message id + scenario

2. Each class has its own namespace, so a component can have the same name or id as a code set, for example. You may want to avoid that, but it is allowed by the XML schema.

**Comment by YuvalCohen** [comment]
Can one please confirm that:
name and id attributes are required attributes in: 
- fixr:message
- fixr:component
- fixr:group
- fixr:field
- fixr:codeset

Whilst scenario is an optional attribute in all the above.

Also,
Can one please confirm that the above is also true for  fixr:code  ?
according to [line 162](https://github.com/FIXTradingCommunity/fix-orchestra/blob/master/repository2016/src/main/resources/xsd/repositorytypes2016.xsd) 
Was this the intention (each code should have an id) ?

**Comment by donmendelson** [comment]
Yes, all of the message elements have a name and a numeric ID. Everyone who knows FIX knows field tags. What is less well know, FIX Repository always had numeric IDs for messages and components as well, but they aren't displayed in specs or FIXimate. Generally, it is better to use numeric IDs as keys since comparison is more efficient than string comparison, and you don't have issues with capitalization, etc. 

In the working group, we had a lot of discussion about creating a unique, persistent ID for all objects. [Object Identifier](http://www.oid-info.com/) (OID) was one protocol proposed, but we backed off that. We may reconsider in the future.

If you only have one use case or scenario of a message or element, you do not need to specify it. The XML schema provides a default value of "base".

**Comment by YuvalCohen** [comment]
> Yes, all of the message elements have a name and a numeric ID. Everyone who knows FIX knows field tags. What is less well know, FIX Repository always had numeric IDs for messages and components as well, but they aren't displayed in specs or FIXimate. Generally, it is better to use numeric IDs as keys since comparison is more efficient than string comparison, and you don't have issues with capitalization, etc.
> 
> In the working group, we had a lot of discussion about creating a unique, persistent ID for all objects. [Object Identifier](http://www.oid-info.com/) (OID) was one protocol proposed, but we backed off that. We may reconsider in the future.
> 
> If you only have one use case or scenario of a message or element, you do not need to specify it. The XML schema provides a default value of "base".

And what about fixr:code ? does it requires attributes: name and numeric id ? (or value is sufficient)?

**Comment by donmendelson** [comment]
All of the message elements use the same attribute group. Name and id are required, scenario defauts to "base", and abbrName is optional.
```xml
<xs:attributeGroup name="oidGrp">
	<xs:annotation>
		<xs:documentation>The identifiers of a message element</xs:documentation>
	</xs:annotation>
	<xs:attribute name="id" type="fixr:id_t" use="required">
		<xs:annotation>
			<xs:documentation>Numeric identifier generally must be unique within a file for an element type, e.g. unique field tag</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="name" type="fixr:Name_t" use="required"/>
	<xs:attribute name="abbrName" type="fixr:Abbreviation_t"/>
	<xs:attribute name="scenario" type="fixr:Scenario_t" default="base">
		<xs:annotation>
			<xs:documentation>The use case of an element, distinguished by workflow, asset class, etc.</xs:documentation>
		</xs:annotation>
	</xs:attribute>
</xs:attributeGroup>
```
