### ISSUE TITLE
Question: How to create basic rules

### ISSUE THREAD

**Issue by YuvalCohen** [FIXTradingCommunity/fix-orchestra#89]
Please provide sample code to define the following (very basic) rules in Orchestra:

1. field 1 is required if and only if field 2 exists
1. field 1 and field 2 are mutually exclusive (either 1 or 2 is required, but not both).
1. Same as above 2 questions, but replace fields with component

Also nice to understand:

4. field 1 is required if field 2 exists
1. field 1 is required if field 2 is equal to "some text"
1. field 1 is required if field 2 and 3 exists
1. field 1 is required if field 2 exists and field 3 = "some text"

Many thanks

**Comment by donmendelson** [comment]
The general form of field rule is like this:
```xml
<fixr:fieldRef added="FIX.4.3" updated="FIX.5.0SP2" updatedEP="190" id="567">
	<fixr:rule name="TradSesStatusRejReason" presence="required">
		<fixr:when>TradSesStatus==^RequestRejected</fixr:when>
	</fixr:rule>
	<fixr:annotation>
		<fixr:documentation>Use with TradSesStatus(340) = 6(Request Rejected). </fixr:documentation>
	</fixr:annotation>
</fixr:fieldRef>
```

The `<rule>` element states that presence is changed to required if the Score expression within the `<when>` element evaluates true. (Answers out of order to take simpler cases first.)

Example expressions in answer to your questions:
4. `exists TradeSesStatus`
5. `Text eq "some text"` ("==" is a synonym for "eq" if you prefer)
6. `exists TradeSesStatus and exists TradeSesMode` ("&&" is a synonym for "and" if you prefer)
7. exists TradeSesStatus and Text == "some text"` 

The syntax is essentially the same for a rule on a component or repeating group.

3. Here's an example with a group reference.
```xml
<fixr:groupRef added="FIX.4.4" id="2057">
	<fixr:rule presence="required">
		<fixr:when>SettlInstMode != ^RequestReject</fixr:when>
	</fixr:rule>
	<fixr:annotation>
		<fixr:documentation>Required except where SettlInstMode is 5=Reject SSI request</fixr:documentation>
	</fixr:annotation>
</fixr:groupRef>
```

--more--

**Comment by donmendelson** [comment]
@YuvalCohen what's the distinction between 1 and 4? In 1, if field2 does not exist, is field1 forbidden?

**Comment by donmendelson** [comment]
@YuvalCohen mutually exclusive fields can be expressed with the "oneOf" syntax that you requested. The general form is:

```xml
<fixr:component id="1999" name="Container" which="oneOf">
	<fixr:fieldRef  id="998">
	<fixr:fieldRef  id="999">
</fixr:component>
```

**Comment by YuvalCohen** [comment]
> @YuvalCohen what's the distinction between 1 and 4? In 1, if field2 does not exist, is field1 forbidden?

Thanks very helpful.,
I guess 1 is actually two rules:
A. field 1 is required when field 2 exists
B. field 2 is required when field 1 exists

This is very helpful.

**Comment by donmendelson** [comment]
@YuvalCohen in that case each field would have a rule referring to existence of the other field.

**Comment by YuvalCohen** [comment]
By the way:  inside the when expression, should it be:
`SettlInstMode != ^RequestReject`
or
`SettlInstMode != "RequestReject"`

**Comment by donmendelson** [comment]
`"RequestRejected"` is a literal String.
`^RequestRejected` means the code named RequestRejected (which has literal int value 6)
