### ISSUE TITLE
[Question] Workflow  in an Orchestra File

### ISSUE THREAD

**Issue by nngakosso** [FIXTradingCommunity/fix-orchestra#98]
Hello, just saw your update on tablature confirming what I've been testing that we are not able to represent workflows from there. So besides, coding a workflow directly into the file in xml is there any other mean to do that?

**Comment by donmendelson** [comment]
The workflow feature is under development, not in this project but rather in https://github.com/FIXTradingCommunity/tablature. Feel free to provide requirements for it through the Orchestra working group.
